// CSLauncher.idl : IDL source for CSLauncher
//

// stub for IBoxOfficeRequest, produced header & guids
// same as ICCSRequest
// according to app. 1

import "oaidl.idl";
import "ocidl.idl";

#include "dual.h"

[
	object,
	uuid(A92C9094-EFF4-475E-A54D-4CA3540F2A3B),
	nonextensible,
	helpstring("ICCSRequest Interface"),
#ifdef DUAL_BOXOFFICE
	dual,
#endif
	pointer_default(unique)
]
interface IBoxOfficeRequest : 
#ifdef DUAL_BOXOFFICE
	IDispatch
#else
	IUnknown
#endif
{
	[id(1), helpstring("Send the query to the Box Office")] HRESULT Request([in] BSTR strXML);
};


//	importlib("stdole2.tlb");

[
	uuid(C7D8C15C-F14F-4945-B532-B1BF1FF15A65),
	helpstring("BoxOfficeRequest Class")
]
coclass BoxOfficeRequest
{
	[default] interface IBoxOfficeRequest;
};
