copy daynight_header.txt DayNightSettings.txt

type cam01_DayNight.txt >> DayNightSettings.txt
type cam02_DayNight.txt >> DayNightSettings.txt 
type cam03_DayNight.txt >> DayNightSettings.txt
type cam04_DayNight.txt >> DayNightSettings.txt
type cam17_DayNight.txt >> DayNightSettings.txt
type cam18_DayNight.txt >> DayNightSettings.txt
type cam19_DayNight.txt >> DayNightSettings.txt
type cam20_DayNight.txt >> DayNightSettings.txt
type cam21_DayNight.txt >> DayNightSettings.txt
type cam22_DayNight.txt >> DayNightSettings.txt
type cam23_DayNight.txt >> DayNightSettings.txt
type cam24_DayNight.txt >> DayNightSettings.txt
type cam25_DayNight.txt >> DayNightSettings.txt
type cam26_DayNight.txt >> DayNightSettings.txt
type cam27_DayNight.txt >> DayNightSettings.txt
type cam28_DayNight.txt >> DayNightSettings.txt
type cam29_DayNight.txt >> DayNightSettings.txt
type cam30_DayNight.txt >> DayNightSettings.txt
type cam31_DayNight.txt >> DayNightSettings.txt
type cam32_DayNight.txt >> DayNightSettings.txt
type cam33_DayNight.txt >> DayNightSettings.txt
type cam34_DayNight.txt >> DayNightSettings.txt
type cam35_DayNight.txt >> DayNightSettings.txt
type cam40_DayNight.txt >> DayNightSettings.txt
type cam41_DayNight.txt >> DayNightSettings.txt
type cam42_DayNight.txt >> DayNightSettings.txt
type cam43_DayNight.txt >> DayNightSettings.txt
type cam46_DayNight.txt >> DayNightSettings.txt