..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam01_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam02_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam03_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam04_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam17_01nov05_19_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam18_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam19_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam20_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam21_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam22_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam23_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam24_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam25_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam26_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam27_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam28_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam29_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam30_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam31_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam32_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam33_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam34_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam35_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam40_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam41_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam42_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam43_01nov05_20_video.avd
..\__release\CSAutoDayNightLearn.exe f:\day-night-test-video\cam46_01nov05_20_video.avd
