//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by f:\Project\VCproject\_Elvees\CinemaSec\CSClient\Res\Ru\CSClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PARAMETER_PAGE              101
#define IDR_HTML_CAMERADIALOG           103
#define IDR_MAINFRAME                   128
#define IDS_NO_IMAGE                    129
#define IDR_TOOLBAR1                    130
#define IDS_EXC_VIDEO_SERVER            130
#define IDS_EXC_VIDEO_IMAGE             131
#define IDS_EXC_INVALID_IMAGE_FILE      132
#define IDR_VIDEO_VIEW                  133
#define IDR_GaugeHallTYPE               134
#define IDR_GaugeHall                   135
#define IDR_GrabMode                    136
#define IDR_ArchiveMode                 137
#define IDR_AlgoDebug                   139
#define IDR_VideoToolbar                140
#define IDR_TrainData                   141
#define IDR_REPORT_VIEW                 142
#define IDR_DIAGNOSTIC_VIEW             143
#define IDR_TIMETABLE_VIEW              144
#define IDR_BOXOFFICE_VIEW              145
#define IDR_SETTINGS_VIEW               146
#define IDR_LOG_VIEW                    147
#define INDICATOR_INDEX                 150
#define INDICATOR_FPS                   151
#define INDICATOR_SPEED                 152
#define INDICATOR_CURSOR                153
#define INDICATOR_DROPPED_FRAME         154
#define IDS_VIEW_VIDEO                  160
#define IDS_VIEW_ARCHIVE                161
#define IDS_VIEW_DIAGNOSTIC             162
#define IDS_VIEW_REPORT                 163
#define IDS_VIEW_ALGORITHM              164
#define IDS_VIEW_TRAINDATA              165
#define IDS_VIEW_BOXOFFICE              166
#define IDS_VIEW_TIMETABLE              167
#define IDS_VIEW_SETTINGS               168
#define IDS_VIEW_LOG                    169
#define IDS_LONGOPERATION               180
#define IDR_CSCLIETYPE                  200
#define IDB_CHAIR_CONTENT               201
#define IDR_PrepareData                 202
#define IDD_OFFSET_CHAIR                204
#define IDD_VIDEO_STAT                  205
#define IDD_DIALOG1                     209
#define IDD_ARCHIVE_STAT                209
#define IDD_DIALOG_TABLE                210
#define IDD_VIDEO_CONTROL               210
#define IDR_SEEK_BAR                    211
#define IDR_VIDEO_RANGE                 212
#define IDD_TIMETABLE                   213
#define IDD_BOXOFFICE                   213
#define IDB_BITMAP1                     214
#define IDB_ARCHIVE_REFRESH             215
#define IDD_ALGO_SETTINGS               218
#define IDD_ALGO_TIMETABLE              219
#define IDD_REPORT                      223
#define IDD_DIAGNOSTIC                  224
#define IDB_BITMAP2                     225
#define IDB_DIAGNOSTIC                  225
#define IDR_TOOLBAR2                    226
#define IDD_LAYOUT                      228
#define IDD_ROOM_SELECT                 229
#define IDD_GRAB_CAMERA                 230
#define IDA_GEAR                        230
#define IDD_GRAB_FILE                   231
#define IDD_RENUMBER                    232
#define IDD_SELECT_ROOM                 233
#define IDD_DIALOG2                     234
#define IDD_LOG                         234
#define IDR_HTML1                       235
#define IDD_FILE_TRANSFER               236
#define ID_HTML_REPORT_CSS              300
#define ID_HTML_REPORT1_XSL             301
#define IDC_STATIC_CSCLIENT_VERSION     1000
#define IDC_RADIO_VIDEOFILE             1001
#define IDC_RADIO_CAMERA                1002
#define IDC_EDIT_IMAGEFILE              1003
#define IDC_EDIT_VIDEOFILE0             1004
#define IDC_EDIT_VIDEOFILE2             1005
#define IDC_EDIT_VIDEOFILE4             1006
#define IDC_EDIT_VIDEOFILE1             1007
#define IDC_EDIT_VIDEOFILE3             1008
#define IDC_EDIT_VIDEOFILE5             1009
#define IDC_PROGRESS_GRAB               1010
#define IDC_EDIT1                       1012
#define IDC_EDIT_DOWN                   1012
#define IDC_EDIT_TIMEAFTER              1012
#define IDC_TIME_BEGIN                  1012
#define IDC_EDIT_CURRENT_FILM           1012
#define IDC_EDIT_ROW_NUMBER             1012
#define IDC_EDIT_MESSAGE_NUMBER         1012
#define IDC_SPIN1                       1013
#define IDC_SPIN_TIMEAFTER              1013
#define IDC_EDIT2                       1013
#define IDC_SPIN_ROW_NUMBER             1013
#define IDC_SPIN_MESSAGE_NUMBER         1013
#define IDC_COMBO1                      1015
#define IDC_COMBO2                      1016
#define IDC_COMBO3                      1017
#define IDC_COMBO4                      1018
#define IDC_COMBO5                      1019
#define IDC_COMBO6                      1020
#define IDC_EDIT_LEFT                   1200
#define IDC_MOVE                        1201
#define IDC_LIST1                       1202
#define IDC_LIST_STAT                   1202
#define IDC_GRID_TIMETABLE              1202
#define IDC_LIST_DIAGNOSTIC             1202
#define IDC_LIST_LOG_MESSAGE            1202
#define IDC_LIST_TRANSFER               1202
#define IDC_COMBO_CINEMA                1203
#define IDC_COMBO_ROOM                  1204
#define IDC_LIST2                       1205
#define IDC_COMBO8                      1206
#define IDC_COMBO_CAMERA_1              1207
#define IDC_COMBO_CAMERA_2              1208
#define IDC_COMBO_CAMERA_3              1209
#define IDC_COMBO_CAMERA_4              1210
#define IDC_COMBO_CAMERA_5              1211
#define IDC_COMBO_CAMERA_6              1212
#define IDC_MONTHCALENDAR1              1213
#define IDC_DATETIMEPICKER1             1214
#define IDC_TIME_END                    1214
#define IDC_TIME_BACKUP                 1214
#define IDC_BEGIN_DATE                  1214
#define IDC_TIME_START                  1214
#define IDC_DATETIME_FROM               1214
#define IDC_DATETIMEPICKER2             1215
#define IDC_DATETIME_TO                 1215
#define IDC_BUTTON_SAVE                 1218
#define IDC_BUTTON_LOAD                 1219
#define IDC_DATE_TIMETABLE              1220
#define IDC_EDIT_TIMEBEFORE             1221
#define IDC_EDIT_PERIOD                 1222
#define IDC_EDIT_AFTER                  1222
#define IDC_SPIN_TIMEBEFORE             1223
#define IDC_SPIN3                       1224
#define IDC_SPIN_PERIOD                 1224
#define IDC_TAB_CINEMA                  1225
#define IDC_TAB_ROOM                    1226
#define IDC_BUTTON_GET_ARCHIVE          1227
#define IDC_BUTTON1                     1230
#define IDC_BUTTON_PLAY                 1230
#define IDC_BUTTON_CREATE               1230
#define IDC_STOP                        1230
#define IDC_BUTTON_GETDATA              1230
#define IDC_CUSTOM1                     1231
#define IDC_STATIC_BAR                  1232
#define IDC_TAB_PARAMETERS              1235
#define IDC_EDIT_BACKUP_START           1236
#define IDC_SPIN_BACKUP_START           1237
#define IDC_EDIT_BACKUP_END             1238
#define IDC_SPIN4                       1239
#define IDC_SPIN_BACKUP_END             1239
#define IDC_BUTTON_APPLY                1240
#define IDC_STATIC_SLIDER               1244
#define IDC_STATIC_RANGE                1245
#define IDC_STATIC_CONTROL              1246
#define IDC_BEGIN_TIME                  1248
#define IDC_END_DATE                    1249
#define IDC_END_TIME                    1250
#define IDC_RADIO_MEASURE_MOMENT        1251
#define IDC_RADIO_FILM                  1252
#define IDC_CHECK_DETAIL                1253
#define IDC_TREE1                       1254
#define IDC_TREE_ROOM                   1254
#define IDC_BUTTON_EXPORT               1255
#define IDC_STATIC_TYPE                 1256
#define IDC_BUTTON_PRINTPREVIEW         1257
#define IDC_TAB2                        1258
#define IDC_BUTTON_EXPORT3              1258
#define IDC_BUTTON_PRINT                1258
#define IDC_STATIC_TB                   1259
#define IDC_SPIN_WIDTH                  1260
#define IDC_EDIT_WIDTH                  1261
#define IDC_SPIN_HEIGHT                 1262
#define IDC_LAYOUT                      1263
#define IDC_TAB_CAMERA                  1265
#define IDC_STATIC_TIME                 1266
#define IDC_STATIC_FRAME                1267
#define IDC_STATIC_TIMEVALUE            1268
#define IDC_STATIC_FRAMEVALUE           1269
#define IDC_PROGRESS1                   1270
#define IDC_PROGRESS_TRANSFER           1270
#define IDC_EDIT_BACKUP_DATE            1271
#define IDC_SPIN_BACKUP                 1272
#define IDC_SPIN_BACKUP_DATE            1272
#define IDC_STATIC_TO                   1273
#define IDC_STATIC_FROM                 1274
#define IDC_RADIO1                      1276
#define IDC_RADIO2                      1277
#define IDC_RADIO3                      1278
#define IDC_STATIC_VRANGE               1279
#define IDC_TAB1                        1281
#define IDC_TAB_LOGWINDOW               1281
#define IDC_DATE_SAVE_FROM              1282
#define IDC_DATE_SAVE_TO                1283
#define IDC_CHECK_AFTER_MIDNIGHT        1284
#define IDC_EDIT_EXC_CONNECTNUMBER      1285
#define IDC_EDIT_EXC_CONNECTTIME        1286
#define IDC_EDIT_EXC_WAITING            1287
#define IDC_EDIT6                       1288
#define IDC_EDIT_EXC_DELAY              1288
#define IDC_SPIN_EXC_CONNECTNUMBER      1290
#define IDC_SPIN_EXC_CONNECTTIME        1291
#define IDC_SPIN_EXC_WAITING            1292
#define IDC_SPIN_EXC_DELAY              1293
#define IDC_STATIC_HTML                 1294
#define IDS_STATE_OFFLINE               2000
#define IDS_STATE_WAIT                  2001
#define IDS_STATE_WORK                  2002
#define IDS_ERROR_CONNECTION            25000
#define IDS_TITLE_TIME                  25001
#define IDS_TITLE_DATE                  25002
#define IDS_TITLE_NUMBER                25003
#define IDS_TITLE_NAME                  25004
#define IDS_TITLE_STARTTIME             25005
#define IDS_TITLE_ENDTIME               25006
#define IDS_ERROR_INVALIDTIME           25007
#define IDS_ERROR_DESC_1                25008
#define IDS_ERROR_DESC_2                25009
#define IDS_ERROR_DESC_3                25010
#define IDS_TAB_CAMERA                  25011
#define IDS_TAB_ROOM                    25012
#define IDS_FILTER_TRAIN                25013
#define IDS_FILTER_CHAIR                25014
#define IDS_FILTER_AVI                  25015
#define IDS_ERROR_FILE_LOADING          25016
#define IDS_ERROR_FILE_SAVING           25017
#define IDS_ERROR_IMAGESIZE             25018
#define IDS_ERROR_DB_LOADING            25019
#define IDS_ERROR_DB_SAVING             25020
#define IDS_ERROR_GRABBER               25021
#define IDS_TITLE_DELETE                25022
#define IDS_ERROR_VIDEO                 25023
#define IDS_ERROR_ITEM                  25024
#define IDS_ERROR_VIDEOIMAGE            25025
#define IDS_ERROR_TABLEITEM             25026
#define IDS_ERROR_ROW                   25027
#define IDS_ERROR_ROWTIME               25028
#define IDS_STRING25029                 25029
#define IDS_ERROR_ROWINTERSECT          25029
#define IDS_TITLE_DEVICE                25030
#define IDS_TITLE_STATE                 25031
#define IDS_TITLE_PARAM_INVALID         25032
#define IDS_SCREENSHOT                  25033
#define IDS_FILTER_IMAGE                25034
#define IDS_FILTER_MODEL                25035
#define IDS_ERROR_SCREENSHOT            25036
#define IDS_ERROR_D3DDEVICE             25037
#define IDS_ERROR_CVMCADCOMPONENT       25038
#define IDS_RENDER_ARRAY                25039
#define IDS_RENDER_MERGE                25040
#define IDS_FMT_ARCHIVE_HEADER          25041
#define IDS_FMT_VIDEO_HEADER            25042
#define IDS_ERROR_DESC_4                25043
#define IDS_ERROR_WRONG_DATE            25044
#define IDS_FMT_LOCATION                25045
#define IDS_RENDER_ID                   25046
#define IDS_TITLE_FT_CAMERA             25047
#define IDS_TITLE_FT_FILESIZE           25048
#define IDS_TITLE_FT_FILENAME           25049
#define IDS_TITLE_FT_SERVER             25050
#define IDS_TITLE_FT_STATE              25051
#define IDS_PREPARE                     25052
#define IDS_ERROR_SERVERREQUEST         25053
#define IDS_FINISHED                    25054
#define IDP_OLE_INIT_FAILED             25055
#define IDS_SHOW_TRANSFER_WINDOW        25056
#define IDS_TITLE_DOWNLOAD              25057
#define IDS_TITLE_TRANSFER_ERROR        25058
#define IDS_ERROR_TRANSFER_EXISTS       25059
#define IDS_FILTER_AVI_AVD              25060
#define IDS_STATE_DISCONNECTED          25061
#define IDS_BO_EXCHANGE                 25062
#define IDS_CREATEREPORT                25063
#define IDS_RECONNECT                   25064
#define IDS_MSG_BO_TIMETABLE            25065
#define IDS_MSG_BO_RESPONSE             25066
#define IDS_MSG_CCS_STATISTICS          25067
#define IDS_MSG_CCS_RESPONSE            25068
#define IDS_MSG_UNKNOWN                 25069
#define IDM_Play_Play_Sequence          32771
#define IDM_Play_Stop_Sequence          32772
#define IDM_Play_First_Frame            32773
#define IDM_Play_NFrames_Backward       32774
#define IDM_Play_Prev_Frame             32775
#define IDM_Play_Next_Frame             32776
#define IDM_Play_NFrames_Forward        32777
#define IDM_Play_Last_Frame             32778
#define IDM_Play_Speed_Up               32779
#define IDM_Play_Speed_Down             32780
#define IDM_Edit_FrameSlider            32781
#define IDM_Edit_ObjectContouring       32782
#define IDM_Edit_CurveAdjusting         32783
#define IDM_Edit_CurveSmoothing         32784
#define IDM_Edit_AdjustingRadius_1      32785
#define IDM_Edit_AdjustingRadius_2      32786
#define IDM_Edit_AdjustingRadius_3      32787
#define IDM_Edit_AdjustingRadius_4      32788
#define IDM_Edit_AdjustingRadius_5      32789
#define IDM_Edit_AdjustingRadius_6      32790
#define IDM_Edit_AdjustingRadius_7      32791
#define IDM_Edit_AdjustingRadius_8      32792
#define IDM_Edit_AdjustingRadius_9      32793
#define IDM_Edit_ObjectSelection        32794
#define IDM_Edit_DeleteObject           32795
#define IDM_AlgoDebug_Start             32796
#define IDM_AlgoDebug_Stop              32797
#define IDM_Parameters                  32798
#define IDM_Param_Default               32799
#define IDM_Param_Load                  32800
#define IDM_Param_Save                  32801
#define ID_IMAGE_ALL                    32809
#define ID_GRAB_BACKGROUND              32810
#define ID_FILE_SAVE_GRAPH              32811
#define ID_FILE_LOAD_GRAPH              32812
#define ID_FILE_SAVE_IMAGE              32813
#define ID_FILE_LOAD_IMAGE              32814
#define ID_DELETE_ITEM                  32815
#define ID_VIEW_VIDEO                   34000
#define ID_VIEW_ARCHIVE                 34001
#define ID_VIEW_DIAGNOSTIC              34002
#define ID_VIEW_TIMETABLE               34003
#define ID_VIEW_REPORT                  34004
#define ID_VIEW_SETTINGS                34005
#define ID_VIEW_ROOM                    34006
#define ID_VIEW_BOXOFFICE               34007
#define ID_VIEW_TRAINDATA               34008
#define ID_VIEW_LOG                     34009
#define ID_IMAGE_1                      35000
#define ID_IMAGE_2                      35001
#define ID_IMAGE_3                      35002
#define ID_IMAGE_4                      35003
#define ID_IMAGE_5                      35004
#define ID_IMAGE_6                      35005
#define ID_FILE_OPEN_GRAPH              36000
#define ID_FILE_OPEN_TRAIN_DATA         36001
#define ID_FILE_SAVE_TRAIN_DATA         36002
#define ID_BUTTON_START_RANGE           36003
#define ID_BUTTON_ADD_RANGE             36006
#define ID_BUTTON_CANCEL_RANGE          36007
#define ID_BUTTON_RANGE_SELECT          36008
#define ID_RANGE_EMPTY                  36008
#define ID_RANGE_HUMAN                  36009
#define ID_RANGE_CLOTHES                36010
#define ID_RANGE_UNKNOWN                36011
#define ID_PREPARE_DATA                 36012
#define ID_MOVE_CHAIRS                  36014
#define ID_SAVE_DB                      36016
#define ID_DB_IMAGE_LOAD                36017
#define ID_DB_LOAD_GRAPH                36018
#define ID_DB_SAVE_GRAPH                36020
#define ID_DB_IMAGE_SAVE                36022
#define ID_NUMBER                       36023
#define ID_IMAGE_GRAB                   36030
#define ID_NEW_GRAPH                    36032
#define ID_BUTTON36033                  36033
#define ID_SHOW_PARAM                   36033
#define ID_VIDEO_PLAY                   36035
#define ID_VIDEO_PAUSE                  36036
#define ID_VIDEO_STOP                   36037
#define ID_VIDEO_SEEK                   36038
#define ID_BUTTON36040                  36040
#define ID_CLONE                        36040
#define ID_SAVE_ALL                     36042
#define ID_BUTTON36043                  36043
#define ID_LOAD_ALL                     36043
#define ID_SETID                        36043
#define ID_BUTTON_PLAY                  36045
#define ID_LAYOUT                       36046
#define ID_GRAB_CAMERA                  36047
#define ID_BUTTON36049                  36049
#define ID_VIDEO_SAVE                   36050
#define ID_VIDEO_START                  36051
#define ID_VIDEO_END                    36052
#define ID_DB_SAVE_MODEL                36053
#define ID_DB_ERASE_MODEL               36054
#define ID_MOVE_IMAGE                   36055
#define ID_BUTTON36056                  36056
#define ID_MOVE_CHAIR                   36056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         36057
#define _APS_NEXT_CONTROL_VALUE         1295
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
